# Setup
title:               David Everly
tagline:             ''
description:         'David Everly'
url:                 https://www.dmeverly.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author: 
  name:              David M. Everly
  url:               https://github.com/dmeverly
  email:             dmeverly@hotmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: 

# Collections
collections:
  completedprojects:
    output: true
  incompleteprojects:
    output: true
  workflowprojects:
    output: true

include:
  - favicon.ico
  - apple-touch-icon.png
  - android-chrome-192x192.png
  - android-chrome-512x512.png
  - favicon-16x16.png
  - favicon-32x32.png