# Setup
title:               David M. Everly
tagline:             'MSN, CRNP, AGACNP-BC'
description:         'I am a Nurse Practitioner with a passion for solving problems with technology'
url:                 https://www.dmeverly.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author: 
  name:              David M. Everly
  url:               https://github.com/dmeverly
  email:             dmeverly@hotmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: 
