# Setup
title:               David Everly
tagline:             ''
description:         'David Everly'
url:                 https://www.dmeverly.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author: 
  name:              David M. Everly
  url:               https://github.com/dmeverly
  email:             dmeverly@hotmail.com

# Gems
plugins:
  - jekyll-paginate-v2

collections:
  completedprojects:
    output: true
  incompleteprojects:
    output: true

pagination:
  enabled: true
  per_page: 5
  paginators:
    - collection: CompletedProjects
      title: "Completed Projects"
      name: Completed_Projects  # this becomes `paginator.completed_projects`
      permalink: '/page/:num/'
    - collection: IncompleteProjects
      title: "Works in Progress"
      name: Incomplete_Projects
      permalink: '/in-progress/page/:num/'

# Custom vars
version:             1.1.0
google_analytics_id: 
