# Setup
title:               David M. Everly
tagline:             'Healthcare & Computer Science Portfolio'
description:         'Nurse Practitioner and Graduate student in Computational AI at Drexel University. Passionate about deep learning, system security, and building things from scratch.'
url:                 https://dmeverly.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author: 
  name:              David M. Everly
  url:               https://github.com/dmeverly
  email:             dmeverly@hotmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: 
