# Setup
title:               David M. Everly
tagline:             'Nurse Practitioner and Student of Machine Learning'
description:         'I am a Nurse Practitioner with interest in solving problems with Machine Learning. Feel free to explore some of my recent work'
url:                 https://dmeverly.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author: 
  name:              David M. Everly
  url:               https://github.com/dmeverly
  email:             dmeverly@hotmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: 
