# Setup
title:               David Everly
tagline:             ''
description:         'Clinical Insight. Intelligent Systems. Secure Solutions.'
url:                 https://www.dmeverly.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author: 
  name:              David M. Everly
  url:               https://github.com/dmeverly
  email:             dmeverly@hotmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: 
